name: CI Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build knockd
      run: go build -o knockd ./knockd

    - name: Build kk
      run: go build -o kk ./kk

    - name: Test cross-compilation
      run: |
        GOOS=linux GOARCH=amd64 go build -o kk-linux ./kk
        GOOS=darwin GOARCH=amd64 go build -o kk-darwin ./kk
        GOOS=windows GOARCH=amd64 go build -o kk-windows.exe ./kk